//Tabla userProgress
[
    {
        termModifiers: {
            1: "muted",
            15: "highlighted",
            16: "muted",
        },
    },
];

[{}];

[
    {
        1: {
            0: "learned",
            1: "learned",
            lastTest: {
                score: { "01012024": 2 },
                date: "2024-01-09T12:13:48.510Z",
                multiple: [
                    {
                        prompt: "わたしは、チリじんです。",
                        expected: "Yo soy chileno.",
                        answer: "Yo soy japones.",
                        correct: false,
                    },
                    {
                        prompt: "わたしは、エンジニアです。",
                        expected: "Yo soy ingeniero.",
                        answer: "Yo soy ingeniero.",
                        correct: true,
                    },
                    {
                        prompt: "あなたは、チリじんですか",
                        expected: "Usted es chileno?",
                        answer: "Usted es americano?",
                        correct: false,
                    },
                    {
                        prompt: "カスエラは、たべものですか",
                        expected: "Cazuela es comida?",
                        answer: "Cazuela es salado?",
                        correct: false,
                    },
                    {
                        prompt: "ともだちのかのじょのかばんです。",
                        expected: "Es la cartera de la polola de mi amig@.",
                        answer: "Es la cartera de la polola de mi amig@.",
                        correct: true,
                    },
                ],
                drag: [
                    {
                        prompt: "Nihonshu no es un bebestible de Chile.",
                        expected:
                            "にほんしゅは、チリののみものじゃありません。",
                        answer: "にほんしゅ",
                        correct: false,
                    },
                    {
                        prompt: "Hiragana es idioma Japones?",
                        expected: "ひらがなは、にほんごですか？",
                        answer: "にほんご",
                        correct: false,
                    },
                    {
                        prompt: "El Sushi es comida de Japon. Omuraisu tambien.",
                        expected:
                            "すしは、にほんのたべものです。オムライスもです。",
                        answer: "は、",
                        correct: false,
                    },
                ],
                timer: { totalSeconds: 11, seconds: 11, minutes: 0, hours: 0 },
            },
            j0: "learning",
            j1: "learning",
            highScore: {
                score: { "01012024": 4 },
                date: "2024-01-05T23:04:47.903Z",
                multiple: [
                    {
                        prompt: "わたしは、チリじんです。",
                        expected: "Yo soy chileno.",
                        answer: "Yo soy chileno.",
                        correct: true,
                    },
                    {
                        prompt: "あなたは、ねこではありません。",
                        expected: "Usted no es gato.",
                        answer: "Usted no es gato.",
                        correct: true,
                    },
                    {
                        prompt: "あなたは、チリじんですか",
                        expected: "Usted es chileno?",
                        answer: "Usted es chileno?",
                        correct: true,
                    },
                    {
                        prompt: "カスエラは、たべものですか",
                        expected: "Cazuela es comida?",
                        answer: "Cazuela es comida?",
                        correct: true,
                    },
                    {
                        prompt: "ピスコラは、チリののみものです。チチャもです。",
                        expected:
                            "Piscola es un trago de chile. Chicha tambien.",
                        answer: "Piscola es un jugo de chile. Chicha no.",
                        correct: false,
                    },
                ],
                drag: [
                    {
                        prompt: "Goku no es una mujer.",
                        expected: "ごくうは、おんなのひとではありません。",
                        answer: "ありません。",
                        correct: false,
                    },
                    {
                        prompt: "Usted es ingeniero?",
                        expected: "あなたは、エンジニアですか？",
                        answer: "あなた",
                        correct: false,
                    },
                    {
                        prompt: "Mari san es tu amiga?",
                        expected: "まりさんは、あなたのともだちですか？",
                        answer: "ともだち",
                        correct: false,
                    },
                ],
                timer: { totalSeconds: 23, seconds: 23, minutes: 0, hours: 0 },
            },
        },
        11: {
            0: "learned",
            1: "learning",
            2: "learned",
            3: "learning",
            4: "learned",
            5: "learning",
            6: "learned",
            7: "learned",
            8: "learning",
            9: "learned",
            10: "learning",
            11: "learning",
            12: "learned",
            13: "learned",
            14: "learned",
            15: "learned",
            16: "learned",
            17: "learned",
            18: "learned",
            19: "learned",
            20: "learned",
            21: "learned",
            22: "learned",
            23: "learned",
            24: "learned",
            25: "learned",
            26: "learned",
            27: "learned",
            28: "learned",
            29: "learned",
            30: "learned",
            31: "learned",
            32: "learned",
            33: "learned",
            34: "learned",
            35: "learned",
            36: "learned",
            37: "learned",
            38: "learned",
            39: "learned",
            40: "learned",
            41: "learned",
            42: "learned",
            43: "learned",
            44: "learned",
            45: "learned",
            46: "learning",
            47: "learned",
            48: "learning",
            49: "learned",
            50: "learned",
            51: "learned",
            52: "learned",
            53: "learned",
            54: "learned",
            55: "learned",
            56: "learned",
            57: "learned",
            58: "learned",
            59: "learned",
            60: "learned",
        },
        501: {
            0: "learning",
            1: "learned",
            2: "learning",
            3: "learning",
            4: "learning",
            5: "learned",
            6: "learned",
            7: "learning",
            8: "learning",
            9: "learned",
            10: "learning",
            11: "learning",
            12: "learned",
            13: "learning",
            14: "learning",
            15: "learning",
            16: "learned",
            17: "learned",
            18: "learned",
            19: "learned",
            20: "learning",
            21: "learned",
            22: "learned",
            23: "learning",
            24: "learning",
            25: "learning",
            26: "learned",
            27: "learning",
            28: "learning",
            29: "learning",
            30: "learning",
            31: "learning",
            32: "learning",
            33: "learning",
            34: "learning",
            j0: "learning",
            j1: "learning",
            j2: "learned",
        },
        601: {
            0: "learning",
            1: "learning",
            2: "learning",
            3: "learned",
            4: "learning",
            5: "learned",
            6: "learning",
            7: "learning",
            8: "learning",
            9: "learned",
            10: "learning",
            11: "learning",
            12: "learning",
            13: "learning",
            14: "learned",
            15: "learning",
            16: "learning",
            17: "learning",
            18: "learning",
            19: "learned",
            20: "learning",
            21: "learning",
            22: "learned",
            23: "learning",
            24: "learning",
            25: "learned",
            26: "learned",
            27: "learning",
            28: "learning",
            29: "learning",
            30: "learning",
            31: "learned",
            32: "learned",
            33: "learned",
            34: "learned",
            35: "learning",
            36: "learning",
            37: "learning",
        },
        701: {
            0: "learned",
            1: "learned",
            2: "learned",
            3: "learned",
            4: "learned",
            5: "learned",
            6: "learned",
            7: "learned",
            8: "learned",
            9: "learned",
            10: "learned",
            11: "learned",
            12: "learned",
            13: "learning",
            14: "learned",
            15: "learned",
            16: "learned",
            17: "learning",
            18: "learning",
            19: "learned",
            20: "learned",
            21: "learned",
            22: "learned",
            23: "learning",
            24: "learned",
            25: "learned",
            26: "learned",
            27: "learned",
            28: "learned",
            29: "learned",
            30: "learned",
            31: "learned",
            32: "learned",
            33: "learning",
            34: "learned",
            35: "learned",
            36: "learning",
            37: "learned",
            38: "learning",
            39: "learned",
            40: "learning",
            41: "learned",
            42: "learned",
            43: "learned",
            44: "learning",
            45: "learning",
            46: "learning",
            47: "learning",
            48: "learned",
            49: "learning",
            50: "learned",
            51: "learned",
            52: "learned",
            53: "learned",
            j0: "learned",
            j14: "learned",
            j52: "learned",
            j41: "learned",
            j50: "learned",
            j32: "learned",
            j11: "learned",
            j7: "learned",
            j28: "learned",
            j22: "learned",
            j1: "learned",
            j40: "learning",
            j19: "learned",
            j23: "learned",
            j37: "learned",
            j29: "learned",
            j48: "learned",
            j9: "learned",
            j46: "learned",
            j27: "learned",
            j3: "learned",
            j33: "learned",
            j49: "learning",
            j44: "learned",
            j10: "learned",
            j12: "learned",
            j5: "learned",
            j6: "learned",
            j45: "learning",
            j17: "learned",
            j16: "learned",
            j43: "learned",
            j18: "learned",
            j34: "learned",
            j51: "learned",
            j47: "learned",
            j31: "learned",
            j25: "learned",
            j26: "learned",
            j24: "learned",
            j53: "learned",
            j35: "learned",
            j21: "learned",
            j30: "learned",
            j20: "learned",
            j39: "learned",
            j2: "learned",
            j38: "learned",
            j15: "learned",
            j13: "learned",
            j36: "learned",
            j4: "learned",
            j42: "learned",
            j8: "learned",
        },
        702: {
            0: "learned",
            1: "learned",
            2: "learned",
            3: "learned",
            4: "learned",
            5: "learned",
            6: "learned",
            7: "learned",
            8: "learned",
            9: "learned",
            10: "learned",
            11: "learned",
            12: "learning",
            13: "learned",
            14: "learned",
            15: "learned",
            16: "learned",
            17: "learned",
            18: "learned",
            19: "learned",
            20: "learned",
            21: "learned",
            22: "learned",
            23: "learned",
            24: "learned",
            25: "learned",
            26: "learned",
            27: "learned",
            28: "learned",
            29: "learned",
            30: "learned",
            31: "learned",
            32: "learned",
            33: "learning",
            34: "learned",
            35: "learned",
            36: "learned",
            37: "learning",
            38: "learned",
            39: "learned",
            40: "learned",
            41: "learned",
            42: "learning",
            43: "learned",
            44: "learned",
            45: "learned",
            46: "learned",
            47: "learned",
            48: "learned",
            49: "learned",
            50: "learned",
            51: "learned",
            52: "learned",
            53: "learned",
            54: "learned",
            55: "learned",
            56: "learning",
            57: "learned",
            58: "learning",
            59: "learned",
            60: "learned",
            61: "learned",
            62: "learned",
            63: "learned",
            64: "learned",
            65: "learned",
            66: "learned",
            67: "learning",
            68: "learned",
            69: "learned",
            70: "learned",
            71: "learned",
            72: "learned",
            73: "learning",
            74: "learned",
            75: "learned",
            76: "learned",
            77: "learned",
            78: "learned",
            79: "learned",
            80: "learned",
            81: "learned",
            j31: "learning",
            j24: "learned",
            j62: "learned",
            j44: "learned",
            j47: "learned",
            j75: "learned",
            j66: "learned",
            j37: "learning",
            j72: "learned",
            j41: "learned",
            j58: "learning",
            j6: "learned",
            j32: "learned",
            j69: "learned",
            j8: "learned",
            j68: "learned",
            j64: "learned",
            j51: "learned",
            j56: "learning",
            j29: "learned",
            j36: "learned",
            j25: "learned",
            j35: "learned",
            j12: "learned",
            j70: "learned",
            j18: "learned",
            j42: "learning",
            j17: "learned",
            j33: "learned",
            j65: "learned",
            j4: "learned",
            j48: "learned",
            j50: "learned",
            j38: "learned",
            j39: "learned",
            j45: "learned",
            j15: "learned",
            j80: "learned",
            j34: "learned",
            j54: "learned",
            j49: "learned",
            j13: "learning",
            j76: "learned",
            j23: "learned",
            j27: "learned",
            j0: "learned",
            j1: "learned",
            j14: "learned",
            j26: "learned",
            j3: "learning",
            j19: "learned",
            j77: "learned",
            j60: "learned",
            j10: "learned",
            j73: "learning",
            j43: "learned",
            j16: "learned",
            j81: "learned",
            j7: "learned",
            j52: "learned",
            j28: "learned",
            j74: "learned",
            j59: "learned",
            j22: "learned",
            j67: "learned",
            j79: "learned",
            j20: "learned",
            j78: "learned",
            j71: "learned",
            j9: "learned",
            j57: "learned",
            j5: "learned",
            j40: "learned",
            j11: "learned",
            j63: "learned",
            j2: "learned",
            j21: "learned",
            j61: "learned",
            j55: "learned",
            j30: "learned",
            j53: "learned",
            j46: "learning",
            lastTest: {
                score: { "09012024": 3 },
                date: "2024-01-14T14:27:08.953Z",
                multiple: [
                    {
                        prompt: "Japones(a) te pregunto「Otearai wa doko desuka?」como puedes responder?",
                        expected: "Kochira desu.",
                        answer: "Kore desu.",
                        correct: false,
                    },
                    {
                        prompt: "Cuando quieres saber una palabra EN JAPONES, como tenias que preguntar?",
                        expected: "XXX wa nihongo de nandesuka?",
                        answer: "XXX wa nihongo de nandesuka?",
                        correct: true,
                    },
                    {
                        prompt: "Cuando ves a la persona por PRIMERA VEZ, como tienes que saludar?",
                        expected:
                            "Hajimemashite! Watashi wa Ferunando desu.Yoroshiku onegaishimasu",
                        answer: "Ohayou gozaimasu! Watashi wa Ferunando desu.Yoroshiku onegaishimasu",
                        correct: false,
                    },
                    {
                        prompt: "Estas caminando en plaza soto mayor y pasando donde bomberos, que vas a decir?",
                        expected: "Kore wa shoubousha desu.",
                        answer: "Kore wa chiri desu.",
                        correct: false,
                    },
                    {
                        prompt: "Estas caminando en plaza soto mayor y casi llegando al acensor, que vas a decir?",
                        expected: "Are wa asenso-ru desu.",
                        answer: "Are wa asenso-ru desu.",
                        correct: true,
                    },
                    {
                        prompt: "Estamos en el restaurante, quieres explicar sobre el Menu del dia, como puedes explicar ?",
                        expected:
                            "Zensai wa Su-pu desu.Mein wa Oniku desu. Deza-to wa Chokore-to desu.",
                        answer: "Sarada desu.Oniku desu.Chokore-to desu.",
                        correct: false,
                    },
                    {
                        prompt: 'Japones(a) mirando "$100" en asensor, y quieres decir 「Ese es precio (de ascensor).」como puedes decir?',
                        expected:
                            "Kore wa ryoukin desu.(Kore wa asenso-ru no ryoukin desu.)",
                        answer: "Kore wa norimono desu.(Kore wa asenso-ru no norimono desu.)",
                        correct: false,
                    },
                    {
                        prompt: "Japones(a) te pregunto mirando estatua de sotomayor 「Sore wa nandesuka?」como puedes responder?",
                        expected: "Sore wa Sotomajyo-ru hiroba desu.",
                        answer: "Sore wa Kafe desu.",
                        correct: false,
                    },
                    {
                        prompt: "Japones(a) te pregunto teniendo un vino tinto a su mano「Kore wa Jyu-su desuka?」como puedes responder?",
                        expected: "Iie, Jyu-su jya arimasen. Aka wain desu.",
                        answer: "Iie, Jyu-su jya arimasen. Aka wain desu.",
                        correct: true,
                    },
                ],
                drag: [],
                timer: { totalSeconds: 4, seconds: 4, minutes: 0, hours: 0 },
            },
            highScore: {
                score: { "09012024": 9 },
                date: "2024-01-11T22:30:07.833Z",
                multiple: [
                    {
                        prompt: "Cuando quieres saber una palabra EN JAPONES, como tenias que preguntar?",
                        expected: "XXX wa nihongo de nandesuka?",
                        answer: "XXX wa nihongo de nandesuka?",
                        correct: true,
                    },
                    {
                        prompt: "Japones(a) te pregunto「Otearai wa doko desuka?」como puedes responder?",
                        expected: "Kochira desu.",
                        answer: "Kochira desu.",
                        correct: true,
                    },
                    {
                        prompt: "Cuando ves una persona que esta mirando para alla, para aca... que vas a decir a esta persona?",
                        expected: "Daijyoubu desuka?",
                        answer: "Daijyoubu desuka?",
                        correct: true,
                    },
                    {
                        prompt: "Estamos en el restaurante, quieres explicar sobre el Menu del dia, como puedes explicar ?",
                        expected:
                            "Zensai wa Su-pu desu.Mein wa Oniku desu. Deza-to wa Chokore-to desu.",
                        answer: "Zensai wa Su-pu desu.Mein wa Oniku desu. Deza-to wa Chokore-to desu.",
                        correct: true,
                    },
                    {
                        prompt: "Estas caminando en plaza soto mayor y casi llegando al acensor, que vas a decir?",
                        expected: "Are wa asenso-ru desu.",
                        answer: "Are wa asenso-ru desu.",
                        correct: true,
                    },
                    {
                        prompt: "Estas caminando en plaza soto mayor y pasando donde bomberos, que vas a decir?",
                        expected: "Kore wa shoubousha desu.",
                        answer: "Kore wa shoubousha desu.",
                        correct: true,
                    },
                    {
                        prompt: "Japones(a) te pregunto mirando a la iglesia catolica 「Are wa nandesuka?」como puedes responder?",
                        expected: "Katorikku no kyoukai desu.",
                        answer: "Katorikku no kyoukai desu.",
                        correct: true,
                    },
                    {
                        prompt: 'Japones(a) mirando "$100" en asensor, y quieres decir 「Ese es precio (de ascensor).」como puedes decir?',
                        expected:
                            "Kore wa ryoukin desu.(Kore wa asenso-ru no ryoukin desu.)",
                        answer: "Kore wa ryoukin desu.(Kore wa asenso-ru no ryoukin desu.)",
                        correct: true,
                    },
                    {
                        prompt: "Japones(a) te pregunto mirando la carta de restaurante, 「Carne de vacuno wa oniku desuka?」como puedes responder?",
                        expected: "Hai, oniku desu. Gyuu niku desu.",
                        answer: "Hai, oniku desu. Gyuu niku desu.",
                        correct: true,
                    },
                ],
                drag: [],
                timer: { totalSeconds: 157, seconds: 37, minutes: 2, hours: 0 },
            },
        },
        703: {
            0: "learned",
            1: "learned",
            2: "learned",
            3: "learned",
            4: "learning",
            5: "learned",
            6: "learned",
            7: "learned",
            8: "learned",
            9: "learned",
            10: "learned",
            11: "learned",
            12: "learned",
            13: "learned",
            14: "learned",
            15: "learned",
            16: "learning",
            17: "learned",
            18: "learned",
            19: "learned",
            20: "learned",
            21: "learned",
            22: "learned",
            23: "learning",
            24: "learned",
            25: "learning",
            26: "learning",
            27: "learning",
            28: "learned",
            29: "learned",
            30: "learning",
            31: "learned",
            32: "learned",
            33: "learned",
            34: "learned",
            35: "learned",
            36: "learned",
            37: "learned",
            38: "learned",
            39: "learning",
            40: "learned",
            41: "learned",
            42: "learned",
            43: "learned",
            44: "learning",
            45: "learned",
            46: "learned",
            47: "learning",
            48: "learned",
            49: "learned",
            50: "learned",
            51: "learned",
            52: "learned",
            53: "learned",
            54: "learned",
            55: "learned",
            56: "learned",
            57: "learned",
            58: "learned",
            59: "learned",
            60: "learned",
            61: "learned",
            62: "learned",
            63: "learned",
            64: "learned",
            65: "learned",
            66: "learned",
            67: "learned",
            68: "learned",
            69: "learned",
            70: "learned",
            71: "learned",
            72: "learned",
            73: "learning",
            74: "learning",
            75: "learned",
            j8: "learned",
            j10: "learned",
            j32: "learned",
            j28: "learned",
            j34: "learned",
            j6: "learned",
            j41: "learned",
            j49: "learned",
            j3: "learning",
            j7: "learned",
            j69: "learning",
            j11: "learned",
            j1: "learned",
            j0: "learned",
            j4: "learned",
            j25: "learning",
            j53: "learned",
            j67: "learning",
            j68: "learned",
            j62: "learned",
            j35: "learned",
            j20: "learned",
            j47: "learning",
            j59: "learned",
            j2: "learned",
            j56: "learned",
            j26: "learned",
            j33: "learned",
            j51: "learning",
            j27: "learned",
            j61: "learning",
            j44: "learning",
            j12: "learned",
            j16: "learned",
            j19: "learned",
            j42: "learned",
            j54: "learned",
            j55: "learned",
            j72: "learned",
            j63: "learned",
            j58: "learned",
            j22: "learned",
            j65: "learned",
            j37: "learned",
            j74: "learning",
            j23: "learning",
            j75: "learned",
            j24: "learned",
            j39: "learned",
            j30: "learned",
            j15: "learned",
            j52: "learned",
            j66: "learned",
            j60: "learned",
            j21: "learned",
            j40: "learned",
            j71: "learning",
            j31: "learned",
            j9: "learned",
            j14: "learned",
            j73: "learning",
            j17: "learned",
            j48: "learned",
            j64: "learned",
            j13: "learned",
            j38: "learned",
            j29: "learned",
            j70: "learned",
            j43: "learned",
            j50: "learned",
            j36: "learned",
            j5: "learning",
            j57: "learned",
            j46: "learned",
            j45: "learned",
            j18: "learned",
            lastTest: {
                score: { 24012024: 2 },
                date: "2024-01-25T00:06:12.859Z",
                multiple: [
                    {
                        prompt: "Cuando hay Henna hito/Abunai hito en la calle, pero, para los japoneses les llamo la atencion y sacando la foto, grabando video... que vas a decir?",
                        expected:
                            "Sumimasen! Shashin wo toranaide kudasai./Bideo wo toranaide kudasai.",
                        answer: "Sumimasen! Shashin wo torimashouka?/Bideo wo torimashouka?",
                        correct: false,
                    },
                    {
                        prompt: "Cuando estan caminando hodou un poco mal estado, que vas a decir?",
                        expected: "Ashimoto kiwo tsukete kudasai!",
                        answer: "Aruite kudasai! Mite kudasai!",
                        correct: false,
                    },
                    {
                        prompt: "Cuando caminando hodou y no tiene semaforo pero, quieres cruzar, justamente viene auto un poco cerca... que vas a decir?",
                        expected: "Sukoshi matte kudasai.",
                        answer: "Sukoshi matemo iidesuka?",
                        correct: false,
                    },
                    {
                        prompt: "Ya llegando la hora de tren, pero, los japoneses estan caminando leeeento... que vas a decir?",
                        expected: "Minasan ! Densha ga kimashita! Isogimashou!",
                        answer: "Minasan ! Nottemo iidesu!",
                        correct: false,
                    },
                    {
                        prompt: "Cuando caminando, henna hito (ho-muresu) pidio dinero a japoneses... que vas a decir?",
                        expected: "Okane wo agenaide kudasai.",
                        answer: "Daijyoubu desu.",
                        correct: false,
                    },
                    {
                        prompt: "Cuando un lugar mas o menos tranquilo, que vas a decir?",
                        expected: "Koko de shashin wo tottemo iidesuyo.",
                        answer: "Koko de shashin wo kattemo iidesuyo.",
                        correct: false,
                    },
                    {
                        prompt: "En la tienda, los japoneses estan viendo lo que hay etc y quieres ofrecer vealo mas cerca o toma en su mano... como vas a decir?",
                        expected: "Douzo! Mite kudasai! Sawatte kudasai!",
                        answer: "Douzo! Mite kudasai! Suwatte kudasai!",
                        correct: false,
                    },
                    {
                        prompt: "En la tienda X los japoneses tiene algo en la mano y caminando... que vas a decir?",
                        expected: "Sore, kaimasuka?",
                        answer: "Sore, kaimasuka?",
                        correct: true,
                    },
                    {
                        prompt: "En el restaurante, el(la) japones(a) se ve que esta buscando el baño... que vas a decir?",
                        expected:
                            "Otearai wa shita ni hitotsu, ueni futatsu arimasu.",
                        answer: "Otearai wa shita ni hitotsu, ueni futatsu arimasu.",
                        correct: true,
                    },
                ],
                drag: [],
                timer: { totalSeconds: 6, seconds: 6, minutes: 0, hours: 0 },
            },
            highScore: {
                score: { 24012024: 2 },
                date: "2024-01-25T00:06:12.859Z",
                multiple: [
                    {
                        prompt: "Cuando hay Henna hito/Abunai hito en la calle, pero, para los japoneses les llamo la atencion y sacando la foto, grabando video... que vas a decir?",
                        expected:
                            "Sumimasen! Shashin wo toranaide kudasai./Bideo wo toranaide kudasai.",
                        answer: "Sumimasen! Shashin wo torimashouka?/Bideo wo torimashouka?",
                        correct: false,
                    },
                    {
                        prompt: "Cuando estan caminando hodou un poco mal estado, que vas a decir?",
                        expected: "Ashimoto kiwo tsukete kudasai!",
                        answer: "Aruite kudasai! Mite kudasai!",
                        correct: false,
                    },
                    {
                        prompt: "Cuando caminando hodou y no tiene semaforo pero, quieres cruzar, justamente viene auto un poco cerca... que vas a decir?",
                        expected: "Sukoshi matte kudasai.",
                        answer: "Sukoshi matemo iidesuka?",
                        correct: false,
                    },
                    {
                        prompt: "Ya llegando la hora de tren, pero, los japoneses estan caminando leeeento... que vas a decir?",
                        expected: "Minasan ! Densha ga kimashita! Isogimashou!",
                        answer: "Minasan ! Nottemo iidesu!",
                        correct: false,
                    },
                    {
                        prompt: "Cuando caminando, henna hito (ho-muresu) pidio dinero a japoneses... que vas a decir?",
                        expected: "Okane wo agenaide kudasai.",
                        answer: "Daijyoubu desu.",
                        correct: false,
                    },
                    {
                        prompt: "Cuando un lugar mas o menos tranquilo, que vas a decir?",
                        expected: "Koko de shashin wo tottemo iidesuyo.",
                        answer: "Koko de shashin wo kattemo iidesuyo.",
                        correct: false,
                    },
                    {
                        prompt: "En la tienda, los japoneses estan viendo lo que hay etc y quieres ofrecer vealo mas cerca o toma en su mano... como vas a decir?",
                        expected: "Douzo! Mite kudasai! Sawatte kudasai!",
                        answer: "Douzo! Mite kudasai! Suwatte kudasai!",
                        correct: false,
                    },
                    {
                        prompt: "En la tienda X los japoneses tiene algo en la mano y caminando... que vas a decir?",
                        expected: "Sore, kaimasuka?",
                        answer: "Sore, kaimasuka?",
                        correct: true,
                    },
                    {
                        prompt: "En el restaurante, el(la) japones(a) se ve que esta buscando el baño... que vas a decir?",
                        expected:
                            "Otearai wa shita ni hitotsu, ueni futatsu arimasu.",
                        answer: "Otearai wa shita ni hitotsu, ueni futatsu arimasu.",
                        correct: true,
                    },
                ],
                drag: [],
                timer: { totalSeconds: 6, seconds: 6, minutes: 0, hours: 0 },
            },
        },
        704: {
            0: "learned",
            1: "learned",
            2: "learning",
            3: "learned",
            4: "learning",
            5: "learned",
            6: "learned",
            7: "learned",
            8: "learned",
            9: "learning",
            10: "learned",
            11: "learned",
            12: "learned",
            13: "learned",
            14: "learned",
            15: "learned",
            16: "learned",
            17: "learned",
            18: "learned",
            19: "learning",
            20: "learned",
            21: "learned",
            22: "learned",
            23: "learned",
            24: "learned",
            25: "learned",
            26: "learned",
            27: "learned",
            28: "learning",
            29: "learned",
            30: "learned",
            31: "learning",
            32: "learned",
            33: "learned",
            34: "learned",
            35: "learned",
            36: "learning",
            37: "learned",
            38: "learned",
            39: "learning",
            40: "learned",
            41: "learned",
            42: "learning",
            43: "learning",
            44: "learning",
            45: "learned",
            46: "learned",
            47: "learned",
            48: "learned",
            49: "learning",
            50: "learned",
            51: "learned",
            52: "learned",
            53: "learned",
            54: "learning",
            55: "learned",
            56: "learned",
            57: "learned",
            58: "learned",
            59: "learning",
            60: "learned",
            61: "learning",
            62: "learned",
            63: "learning",
            64: "learned",
            65: "learned",
            66: "learning",
            67: "learning",
            68: "learned",
            69: "learning",
            70: "learned",
            71: "learning",
            72: "learning",
            73: "learned",
            74: "learned",
            75: "learning",
            76: "learned",
            77: "learning",
            78: "learning",
            79: "learned",
            j16: "learned",
            j8: "learned",
            j20: "learned",
            j49: "learned",
            j76: "learned",
            j29: "learned",
            j4: "learned",
            j7: "learned",
            j67: "learned",
            j22: "learned",
            j6: "learned",
            j31: "learned",
            j64: "learned",
            j5: "learned",
            j61: "learned",
            j56: "learned",
            j73: "learned",
            j71: "learned",
            j34: "learned",
            j57: "learned",
            j63: "learned",
            j77: "learned",
            j17: "learned",
            j32: "learned",
            j68: "learned",
            j78: "learned",
            j50: "learned",
            j23: "learned",
            j59: "learned",
            j36: "learned",
            j9: "learned",
            j52: "learned",
            j21: "learned",
            j47: "learned",
            j39: "learned",
            j62: "learned",
            j48: "learned",
            j44: "learned",
            j69: "learned",
            j38: "learned",
            j41: "learned",
            j18: "learned",
            j30: "learned",
            j27: "learned",
            j19: "learned",
            j74: "learned",
            j10: "learned",
            j54: "learned",
            j42: "learned",
            j33: "learned",
            j15: "learned",
            j70: "learned",
            j55: "learned",
            j0: "learned",
            j65: "learned",
            j66: "learned",
            j26: "learned",
            j46: "learned",
            j37: "learned",
            j2: "learned",
            j13: "learned",
            j43: "learned",
            j60: "learned",
            j72: "learning",
            j3: "learned",
            j24: "learned",
            j14: "learned",
            j35: "learned",
            j1: "learned",
            j40: "learned",
            j53: "learned",
            j25: "learned",
            j75: "learned",
            j45: "learned",
            j12: "learned",
            j11: "learned",
            j51: "learned",
            j28: "learned",
            j58: "learned",
            lastTest: {
                score: { 22012024: 3 },
                date: "2024-02-12T00:35:06.301Z",
                multiple: [
                    {
                        prompt: "Japones(a) esta viendo dulce de Chile pero, parece que no ha entendido que es un dulce, que vas a decir?",
                        expected: "Kore wa, Chiri no amai okashi desu.",
                        answer: "Kore wa, Chiri no amai okashi desu.",
                        correct: true,
                    },
                    {
                        prompt: '"Cazuela es una sopa rica de Chile" wa Nihongo de nandesuka?',
                        expected: "Kasuera wa Chiri no oishii su-pu desu.",
                        answer: "Kasuera wa Chiri no shoppai su-pu desu.",
                        correct: false,
                    },
                    {
                        prompt: 'Japones(a) te pregunto "Sero aregure(cerro alegre) wa abunai desuka?", como vas a responder?',
                        expected:
                            "Hai, sukoshi abunai desu. Ki wo tsukete kudasai.",
                        answer: "Iie, Abunaku arimasen desu.Ki wo tsukete kudasai.",
                        correct: false,
                    },
                    {
                        prompt: 'En el restaurante, menu es "Chorillana" y Japones(a) te pregunto "Kore wa Karai desuka?", como vas a responder?',
                        expected:
                            "Iie, Karaku arimasen. Shoppai desu. Soshite Oishii desu.",
                        answer: "Iie, Karaku arimasen. Nigai desu. Soshite Oishii desu.",
                        correct: false,
                    },
                    {
                        prompt: 'En la tienda de regalo, viendo cuchufli de $5000(4 cuchufli en una bolsa), Japones(a) te pregunto "Kono Kuchufuri- wa yasui desuka?",como vas a responder?',
                        expected: "U-n...Yasukunaidesu...",
                        answer: "U-n...Yasuidesu.",
                        correct: false,
                    },
                    {
                        prompt: "En la tienda de regalo, Japones(a) se esta probando un poncho pero, se ve demasiado grande, que vas a decir? ",
                        expected: "Dou desuka ? Ookii desuka?",
                        answer: "Dou desuka ? Ookii desuka?",
                        correct: true,
                    },
                    {
                        prompt: 'Estan viendo "Manjar" y Japones(a) pregunto "Manha-ru wa donna aji desuka?" quieres decir "Es suave(textura) y dulce", como vas a decir?  ',
                        expected:
                            "ManHa-ru wa Yawarakai desu. Soshite amai desu.",
                        answer: "ManHa-ru wa Katai desu. Soshite amai desu.",
                        correct: false,
                    },
                    {
                        prompt: 'En la tienda de regalo, Japones(a) esta viendo sorprendido a un Indio picaro y te pregunto "Kore nandesuka?!", que vas a decir? ',
                        expected:
                            "Kore no namae wa Indio Pikaro desu. Chiri no shukougeihin desu. Kawaii Mapuche no ningyou desu.",
                        answer: "Kore no namae wa Indio Pikaro desu. Chiri no osusume desu. Kawaii Mapuche no ningyou desu.",
                        correct: false,
                    },
                    {
                        prompt: "Estan caminando por el cerro y hay una persona extraña en la calle, que vas a decir?",
                        expected: "Henna hito ga imasu ! ",
                        answer: "Henna hito ga imasu ! ",
                        correct: true,
                    },
                ],
                drag: [],
                timer: { totalSeconds: 30, seconds: 30, minutes: 0, hours: 0 },
            },
            highScore: {
                score: { 22012024: 9 },
                date: "2024-01-22T21:07:44.863Z",
                multiple: [
                    {
                        prompt: 'Japones(a) te pregunto antes de comenzar el tour, "Baruparaiso wa donna machi desuka?", como vas a explicar?',
                        expected: "Baruparaiso wa omoshiroi machi desu.",
                        answer: "Baruparaiso wa omoshiroi machi desu.",
                        correct: true,
                    },
                    {
                        prompt: '"Cazuela es una sopa rica de Chile" wa Nihongo de nandesuka?',
                        expected: "Kasuera wa Chiri no oishii su-pu desu.",
                        answer: "Kasuera wa Chiri no oishii su-pu desu.",
                        correct: true,
                    },
                    {
                        prompt: 'Estan en plaza soto mayor y Japones(a) te pregunto "Kore wa nan desuka?" apuntando hacia la estatua de Arturo Prat, como vas a explicar?',
                        expected:
                            'Kono hito no namae wa "Aruturo puratto desu. Totemo Yuumei na Chiri no Hito desu".',
                        answer: 'Kono hito no namae wa "Aruturo puratto desu. Totemo Yuumei na Chiri no Hito desu".',
                        correct: true,
                    },
                    {
                        prompt: 'En la tienda de regalo, viendo cuchufli de $5000(4 cuchifri en una bolsa), Japones(a) te pregunto "Kono Kuchufuri- wa yasui desuka?",como vas a responder?',
                        expected: "U-n...Yasukunaidesu...",
                        answer: "U-n...Yasukunaidesu...",
                        correct: true,
                    },
                    {
                        prompt: 'Estamos en lugar X que dice "Silencio", que vas a decir?',
                        expected: "Koko wa shizuka ni shimashou.",
                        answer: "Koko wa shizuka ni shimashou.",
                        correct: true,
                    },
                    {
                        prompt: 'En el restaurante, menu es "Chorillana" y Japones(a) te pregunto "Kore wa Karai desuka?", como vas a responder?',
                        expected:
                            "Iie, Karaku arimasen. Shoppai desu. Soshite Oishii desu.",
                        answer: "Iie, Karaku arimasen. Shoppai desu. Soshite Oishii desu.",
                        correct: true,
                    },
                    {
                        prompt: 'En la tienda de regalo, Japones(a) esta viendo sorprendido a un Indio picaro y te pregunto "Kore nandesuka?!", que vas a decir? ',
                        expected:
                            "Kore no namae wa Indio Pikaro desu. Chiri no shukougeihin desu. Kawaii Mapuche no ningyou desu.",
                        answer: "Kore no namae wa Indio Pikaro desu. Chiri no shukougeihin desu. Kawaii Mapuche no ningyou desu.",
                        correct: true,
                    },
                    {
                        prompt: 'En la tienda del regalo, Japones(a) te pregunto "Kore no Aka arimasuka?" y tu sabes que hay variedad de colores, como vas a responder?',
                        expected: "Iroiro na iro ga arimasu.",
                        answer: "Iroiro na iro ga arimasu.",
                        correct: true,
                    },
                    {
                        prompt: "Estan caminando por el cerro y hay una persona extraña en la calle, que vas a decir?",
                        expected: "Henna hito ga imasu ! ",
                        answer: "Henna hito ga imasu ! ",
                        correct: true,
                    },
                ],
                drag: [],
                timer: { totalSeconds: 128, seconds: 8, minutes: 2, hours: 0 },
            },
        },
        705: {
            0: "learned",
            1: "learned",
            2: "learned",
            3: "learned",
            4: "learned",
            5: "learned",
            6: "learned",
            7: "learning",
            8: "learned",
            9: "learning",
            10: "learned",
            11: "learned",
            12: "learned",
            13: "learned",
            14: "learned",
            15: "learned",
            16: "learning",
            17: "learned",
            18: "learning",
            19: "learning",
            20: "learning",
            21: "learned",
            22: "learned",
            23: "learning",
            24: "learned",
            25: "learned",
            26: "learning",
            27: "learning",
            28: "learned",
            29: "learned",
            30: "learned",
            31: "learning",
            32: "learning",
            33: "learned",
            34: "learned",
            35: "learned",
            36: "learned",
            37: "learned",
            38: "learning",
            j16: "learned",
            j18: "learning",
            j31: "learning",
            j5: "learned",
            j1: "learned",
            j15: "learned",
            j4: "learning",
            j36: "learned",
            j38: "learned",
            j27: "learning",
            j9: "learning",
            j24: "learning",
            j33: "learning",
            j21: "learned",
            j19: "learned",
            j8: "learned",
            j25: "learned",
            j3: "learned",
            j14: "learned",
            j10: "learned",
            j28: "learned",
            j13: "learned",
            j35: "learned",
            j34: "learned",
            j30: "learned",
            j0: "learned",
            j32: "learned",
            j37: "learned",
            j2: "learned",
            j23: "learning",
            j12: "learning",
            j17: "learned",
            j6: "learned",
            j20: "learning",
            j11: "learned",
            j7: "learned",
            j22: "learned",
            j26: "learning",
            j29: "learned",
        },
        706: {
            0: "learned",
            1: "learned",
            2: "learned",
            3: "learned",
            4: "learned",
            5: "learned",
            6: "learned",
            7: "learned",
            8: "learned",
            9: "learned",
            10: "learned",
            11: "learned",
            12: "learned",
            13: "learned",
            14: "learned",
            15: "learned",
            16: "learned",
            17: "learned",
            18: "learned",
            19: "learned",
            20: "learned",
            21: "learned",
            22: "learned",
            23: "learned",
            24: "learned",
            25: "learned",
            26: "learned",
            27: "learned",
            28: "learned",
            29: "learned",
            30: "learned",
            31: "learned",
            32: "learned",
            33: "learned",
            34: "learning",
            35: "learning",
            36: "learned",
            37: "learned",
            38: "learned",
            39: "learned",
            40: "learned",
            41: "learned",
            42: "learned",
            43: "learned",
            44: "learning",
            45: "learning",
            46: "learning",
            47: "learned",
            48: "learned",
            49: "learning",
            50: "learned",
            51: "learning",
            j3: "learned",
            j33: "learned",
            j11: "learned",
            j19: "learned",
            j50: "learning",
            j4: "learned",
            j32: "learned",
            j37: "learned",
            j45: "learning",
            j40: "learning",
            j18: "learned",
            j17: "learning",
            j38: "learned",
            j51: "learning",
            j10: "learned",
            j14: "learned",
            j43: "learned",
            j9: "learned",
            j8: "learning",
            j27: "learned",
            j24: "learned",
            j28: "learning",
            j12: "learning",
            j49: "learning",
            j15: "learned",
            j44: "learning",
            j35: "learning",
            j2: "learned",
            j30: "learned",
            j46: "learning",
            j26: "learned",
            j31: "learned",
            j0: "learned",
            j48: "learned",
            j5: "learned",
            j34: "learning",
            j23: "learned",
            j13: "learned",
            j21: "learned",
            j16: "learned",
            j22: "learned",
            j6: "learned",
            j7: "learned",
            j36: "learned",
            j39: "learned",
            j29: "learned",
            j42: "learned",
            j25: "learned",
            j47: "learned",
            j20: "learned",
            j1: "learned",
            j41: "learned",
        },
        707: {
            0: "learned",
            1: "learned",
            2: "learned",
            3: "learned",
            4: "learned",
            5: "learned",
            6: "learned",
            7: "learned",
            8: "learned",
            9: "learned",
            10: "learned",
            11: "learned",
            12: "learned",
            13: "learned",
            14: "learned",
            15: "learned",
            16: "learned",
            17: "learned",
            18: "learning",
            19: "learned",
            20: "learned",
            21: "learned",
            22: "learned",
            23: "learned",
            24: "learned",
            25: "learned",
            26: "learned",
            27: "learned",
            28: "learning",
            29: "learned",
            30: "learned",
            31: "learned",
            32: "learned",
            33: "learned",
            34: "learned",
            35: "learned",
            36: "learned",
            37: "learned",
            38: "learned",
            39: "learned",
            40: "learned",
            41: "learned",
            42: "learned",
            43: "learned",
            44: "learned",
            45: "learned",
            46: "learned",
            j17: "learned",
            j11: "learned",
            j18: "learned",
            j24: "learned",
            j34: "learned",
            j22: "learned",
            j41: "learned",
            j6: "learned",
            j32: "learned",
            j21: "learned",
            j13: "learned",
            j8: "learned",
            j27: "learned",
            j9: "learned",
            j26: "learned",
            j4: "learned",
            j12: "learned",
            j14: "learned",
            j40: "learned",
            j23: "learned",
            j46: "learned",
            j31: "learned",
            j7: "learned",
            j16: "learned",
            j2: "learned",
            j19: "learned",
            j38: "learning",
            j45: "learned",
            j35: "learned",
            j37: "learning",
            j36: "learned",
            j44: "learned",
            j30: "learned",
            j39: "learned",
            j0: "learned",
            j28: "learned",
            j33: "learned",
            j20: "learned",
            j29: "learned",
            j43: "learned",
            j1: "learned",
            j15: "learned",
            j10: "learned",
            j5: "learning",
            j3: "learned",
            j25: "learning",
            j42: "learned",
        },
        708: {
            0: "learned",
            1: "learned",
            2: "learned",
            3: "learned",
            4: "learned",
            5: "learned",
            6: "learned",
            7: "learned",
            8: "learned",
            9: "learned",
            10: "learned",
            11: "learned",
            12: "learning",
            13: "learned",
            14: "learned",
            15: "learned",
            16: "learned",
            17: "learned",
            18: "learned",
            19: "learned",
            20: "learned",
            21: "learned",
            22: "learning",
            23: "learned",
            24: "learned",
            25: "learned",
            26: "learning",
            27: "learned",
            28: "learning",
            29: "learned",
            30: "learning",
            31: "learning",
            32: "learning",
            33: "learning",
            34: "learned",
            35: "learned",
            36: "learned",
            37: "learning",
            38: "learning",
            39: "learned",
            40: "learned",
            41: "learning",
            42: "learning",
            43: "learning",
            44: "learned",
            45: "learning",
            46: "learned",
            47: "learned",
            48: "learned",
            49: "learned",
            50: "learned",
            51: "learning",
            52: "learning",
            53: "learned",
            54: "learned",
            55: "learned",
            56: "learned",
            57: "learned",
            58: "learned",
            59: "learned",
            60: "learned",
            61: "learning",
            62: "learning",
            63: "learning",
            64: "learning",
            65: "learning",
            66: "learned",
            67: "learned",
            68: "learned",
            69: "learned",
            70: "learned",
            71: "learning",
            72: "learning",
            73: "learning",
            74: "learned",
            75: "learning",
            76: "learning",
            77: "learning",
            78: "learning",
            79: "learning",
            80: "learned",
            81: "learning",
            82: "learning",
            83: "learned",
            84: "learned",
            85: "learned",
            86: "learned",
            87: "learned",
            88: "learning",
            89: "learned",
            90: "learned",
            91: "learned",
            92: "learning",
            93: "learning",
            94: "learned",
            95: "learning",
            96: "learning",
            97: "learning",
            98: "learning",
            99: "learned",
            100: "learning",
            101: "learned",
            j3: "learned",
            j13: "learned",
            j1: "learning",
            j6: "learned",
            j17: "learned",
            j14: "learned",
            j8: "learned",
            j9: "learned",
            j10: "learned",
            j0: "learning",
            j7: "learned",
            j18: "learned",
            j12: "learned",
            j15: "learned",
            j4: "learned",
            j11: "learned",
            j2: "learned",
            j5: "learned",
            j16: "learned",
            j33: "learned",
            j41: "learning",
            j34: "learned",
            j30: "learning",
            j29: "learned",
            j20: "learned",
            j25: "learned",
            j39: "learned",
            j35: "learned",
            j22: "learned",
            j23: "learned",
            j40: "learned",
            j26: "learned",
            j24: "learned",
            j36: "learned",
            j19: "learned",
            j27: "learned",
            j38: "learning",
            j32: "learned",
            j31: "learning",
            j28: "learned",
            j21: "learned",
            j37: "learned",
            j42: "learned",
            j60: "learned",
            j51: "learning",
            j48: "learned",
            j52: "learned",
            j53: "learned",
            j45: "learned",
            j61: "learned",
            j47: "learned",
            j68: "learned",
            j59: "learned",
            j50: "learned",
            j46: "learned",
            j56: "learning",
            j74: "learned",
            j69: "learned",
            j49: "learned",
            j44: "learned",
            j64: "learned",
            j58: "learned",
            j70: "learned",
            j57: "learned",
            j63: "learned",
            j65: "learned",
            j72: "learned",
            j75: "learning",
            j73: "learned",
            j71: "learned",
            j54: "learned",
            j55: "learned",
            j66: "learned",
            j43: "learning",
            j62: "learned",
            j67: "learned",
            lastTest: {
                score: { 22012024: 3 },
                date: "2024-02-11T23:13:47.629Z",
                multiple: [
                    {
                        prompt: "Estas guiando y quieres explicar sobre estacion de bomberos que esta en la Plaza Soto mayor, como vas a explicar?",
                        expected:
                            "Koko wa Chiri no hajimete no shoubousho desu.",
                        answer: "Koko wa Chiri no hajimete no shoubousho desu.",
                        correct: true,
                    },
                    {
                        prompt: 'Cual es la diferencia entre "Koko, Soko, Asoko" y "Kochira, Sochira, Achira"?',
                        expected:
                            '"Kochira, Sochira, Achira" mas formal que "Koko, Soko, Asoko".',
                        answer: "No hay diferencia.",
                        correct: false,
                    },
                    {
                        prompt: 'Cuando hablas sobre el objeto y NO sabes como se llama el objeto O simplemente quiere decir "Esto, Eso, Aquello" como se dice? ',
                        expected: "Kore, Sore, Are",
                        answer: "Kono, Sono, Ano",
                        correct: false,
                    },
                    {
                        prompt: "Quieres hablar sobre una iglesia que esta cerca de Japones(a) (Pero no cerca de ti), como vas a explicar?",
                        expected: "Soko wa Chiri no katorikku no kyoukai desu.",
                        answer: "Soko wa Chiri no katorikku no kyoukai desu.",
                        correct: true,
                    },
                    {
                        prompt: 'Estamos cerca del ascensor El Peral y quieres decir "Vamos a tomar el ascensor de ahi.",como vas a decir?',
                        expected: "Soko no Asenso-ru ni norimasu!",
                        answer: "Koko no Asenso-ru ni norimasu!",
                        correct: false,
                    },
                    {
                        prompt: "Estamos viendo la vista desde el cerro y quieres explicar que aquel lugar son las Dunas de Con Con, como vas a explicar?",
                        expected:
                            "Mite kudasai ! Asoko wa chiri no sakyuu desu. KonKon Sakyuu desu.",
                        answer: "Mite kudasai ! Mae wa chiri no sakyuu desu. KonKon Sakyuu desu.",
                        correct: false,
                    },
                    {
                        prompt: 'Estas guiando cerca de otro grupo y Japones(a) te pregunto "Hoka no Gaido san wa dochira desuka?", como vas a responder?',
                        expected: "Achira desu.",
                        answer: "Koko desu.",
                        correct: false,
                    },
                    {
                        prompt: "Japones(a) esta caminando hacia otro lado (alejandose), que vas a decir? ",
                        expected:
                            "Sumimasen! Kochira desu! Kochira ni kite kudasai!",
                        answer: "Sumimasen! Asoko desu! Asoko ni kite kudasai!",
                        correct: false,
                    },
                    {
                        prompt: "Estas guiando en el cerro y quieres enseñar el nombre del cerro que estas caminando, como vas a explicar?",
                        expected:
                            'Koko no oka no namae wa, "Sero Aregure(cerro alegre) desu."',
                        answer: 'Koko no oka no namae wa, "Sero Aregure(cerro alegre) desu."',
                        correct: true,
                    },
                ],
                drag: [],
                timer: { totalSeconds: 43, seconds: 43, minutes: 0, hours: 0 },
            },
            highScore: {
                score: { 22012024: 9 },
                date: "2024-01-22T21:04:23.838Z",
                multiple: [
                    {
                        prompt: 'Cual es la diferencia entre "Koko, Soko, Asoko" y "Kochira, Sochira, Achira"?',
                        expected:
                            '"Kochira, Sochira, Achira" mas formal que "Koko, Soko, Asoko".',
                        answer: '"Kochira, Sochira, Achira" mas formal que "Koko, Soko, Asoko".',
                        correct: true,
                    },
                    {
                        prompt: "Estas guiando y quieres explicar sobre estacion de bomberos que esta en la Plaza Soto mayor, como vas a explicar?",
                        expected:
                            "Koko wa Chiri no hajimete no shoubousho desu.",
                        answer: "Koko wa Chiri no hajimete no shoubousho desu.",
                        correct: true,
                    },
                    {
                        prompt: 'Cuando hablas sobre el objeto y NO sabes como se llama el objeto O simplemente quiere decir "Esto, Eso, Aquello" como se dice? ',
                        expected: "Kore, Sore, Are",
                        answer: "Kore, Sore, Are",
                        correct: true,
                    },
                    {
                        prompt: "Estamos viendo la vista desde el cerro y quieres explicar que aquel lugar son las Dunas de Con Con, como vas a explicar?",
                        expected:
                            "Mite kudasai ! Asoko wa chiri no sakyuu desu. KonKon Sakyuu desu.",
                        answer: "Mite kudasai ! Asoko wa chiri no sakyuu desu. KonKon Sakyuu desu.",
                        correct: true,
                    },
                    {
                        prompt: "Quieres hablar sobre una iglesia que esta cerca de Japones(a) (Pero no cerca de ti), como vas a explicar?",
                        expected: "Soko wa Chiri no katorikku no kyoukai desu.",
                        answer: "Soko wa Chiri no katorikku no kyoukai desu.",
                        correct: true,
                    },
                    {
                        prompt: 'Estamos cerca del ascensor El Peral y quieres decir "Vamos a tomar el ascensor de ahi.",como vas a decir?',
                        expected: "Soko no Asenso-ru ni norimasu!",
                        answer: "Soko no Asenso-ru ni norimasu!",
                        correct: true,
                    },
                    {
                        prompt: "Estas guiando en el cerro y quieres ensenar el nombre del cerro que estas caminando, como vas a explicar?",
                        expected:
                            'Koko no oka no namae wa, "Sero Aregure(cerro alegre) desu."',
                        answer: 'Koko no oka no namae wa, "Sero Aregure(cerro alegre) desu."',
                        correct: true,
                    },
                    {
                        prompt: "Japones(a) esta caminando hacia otro lado (alejandose), que vas a decir? ",
                        expected:
                            "Sumimasen! Kochira desu! Kochira ni kite kudasai!",
                        answer: "Sumimasen! Kochira desu! Kochira ni kite kudasai!",
                        correct: true,
                    },
                    {
                        prompt: "Estas guiando en el cerro y hay varios lugares que se ve como una casa pero, es una galeria del arte, como vas a explicar?",
                        expected:
                            "Soko wa minka jya arimasen. Garou desu. Hairimasenka?",
                        answer: "Soko wa minka jya arimasen. Garou desu. Hairimasenka?",
                        correct: true,
                    },
                ],
                drag: [],
                timer: { totalSeconds: 125, seconds: 5, minutes: 2, hours: 0 },
            },
        },
        709: {
            0: "learned",
            1: "learned",
            2: "learned",
            3: "learned",
            4: "learned",
            5: "learned",
            6: "learned",
            7: "learned",
            8: "learned",
            9: "learned",
            10: "learned",
            11: "learned",
            12: "learned",
            13: "learned",
            14: "learned",
            15: "learned",
            16: "learned",
            17: "learned",
            18: "learned",
            19: "learned",
            20: "learned",
            21: "learned",
            22: "learned",
            23: "learned",
            24: "learned",
            25: "learned",
            26: "learned",
            27: "learned",
            28: "learned",
            29: "learned",
            30: "learned",
            31: "learned",
            32: "learned",
            33: "learned",
            34: "learned",
            35: "learned",
            36: "learned",
            37: "learned",
            38: "learned",
            39: "learned",
            40: "learned",
            41: "learned",
            42: "learned",
            43: "learned",
            44: "learned",
            45: "learned",
            46: "learned",
            47: "learned",
            48: "learned",
            49: "learning",
            50: "learning",
            51: "learned",
            52: "learned",
            53: "learned",
            j15: "learned",
            j42: "learned",
            j52: "learned",
            j1: "learned",
            j30: "learned",
            j14: "learning",
            j19: "learned",
            j7: "learned",
            j51: "learned",
            j25: "learned",
            j18: "learned",
            j32: "learned",
            j37: "learned",
            j23: "learned",
            j8: "learned",
            j5: "learned",
            j29: "learned",
            j13: "learned",
            j9: "learned",
            j38: "learned",
            j39: "learned",
            j44: "learned",
            j20: "learned",
            j0: "learned",
            j2: "learning",
            j24: "learned",
            j50: "learning",
            j10: "learned",
            j22: "learned",
            j35: "learned",
            j46: "learned",
            j40: "learned",
            j16: "learned",
            j36: "learned",
            j47: "learned",
            j27: "learned",
            j53: "learned",
            j33: "learning",
            j6: "learned",
            j17: "learned",
            j41: "learned",
            j49: "learned",
            j12: "learned",
            j48: "learned",
            j26: "learned",
            j43: "learned",
            j31: "learned",
            j4: "learned",
            j45: "learned",
            j28: "learned",
            j11: "learned",
            j3: "learned",
            j34: "learned",
            j21: "learned",
        },
        710: {
            0: "learned",
            1: "learned",
            2: "learned",
            3: "learning",
            4: "learned",
            5: "learned",
            6: "learned",
            7: "learned",
            8: "learned",
            9: "learned",
            10: "learned",
            11: "learning",
            12: "learned",
            13: "learned",
            14: "learned",
            15: "learned",
            16: "learning",
            17: "learning",
            18: "learning",
            19: "learning",
            20: "learned",
            21: "learned",
            22: "learned",
            23: "learned",
            24: "learned",
            25: "learned",
            26: "learned",
            27: "learned",
            28: "learned",
            29: "learned",
            30: "learned",
            31: "learned",
            32: "learned",
            33: "learning",
            34: "learned",
            35: "learned",
            36: "learned",
            37: "learned",
            38: "learned",
            39: "learned",
            40: "learned",
            41: "learned",
            42: "learned",
            43: "learned",
            44: "learned",
            45: "learned",
            j34: "learned",
            j8: "learned",
            j14: "learned",
            j12: "learned",
            j45: "learned",
            j32: "learned",
            j26: "learned",
            j13: "learned",
            j25: "learned",
            j42: "learned",
            j9: "learned",
            j17: "learned",
            j10: "learned",
            j21: "learned",
            j37: "learned",
            j41: "learning",
            j22: "learned",
            j24: "learned",
            j31: "learned",
            j33: "learned",
            j36: "learned",
            j15: "learned",
            j38: "learning",
            j28: "learned",
            j7: "learned",
            j6: "learned",
            j5: "learned",
            j39: "learned",
            j30: "learned",
            j1: "learned",
            j40: "learned",
            j18: "learning",
            j19: "learning",
            j11: "learning",
            j0: "learned",
            j43: "learned",
            j20: "learned",
            j23: "learned",
            j27: "learned",
            j44: "learned",
            j2: "learned",
            j4: "learned",
            j35: "learned",
            j16: "learned",
            j29: "learned",
            j3: "learned",
        },
        711: {
            0: "learning",
            1: "learned",
            2: "learned",
            3: "learned",
            4: "learning",
            5: "learned",
            6: "learned",
            7: "learned",
            8: "learned",
            9: "learned",
            10: "learned",
            11: "learned",
            12: "learned",
            13: "learned",
            14: "learned",
            15: "learned",
            16: "learned",
            17: "learning",
            18: "learned",
            19: "learned",
            20: "learned",
            21: "learned",
            22: "learned",
            23: "learned",
            24: "learned",
            25: "learned",
            26: "learned",
            27: "learning",
            28: "learned",
            29: "learned",
            30: "learned",
            31: "learned",
            32: "learned",
            33: "learned",
            34: "learned",
            35: "learned",
            36: "learned",
            37: "learned",
            38: "learned",
            39: "learned",
            40: "learned",
            41: "learned",
            42: "learned",
            43: "learned",
            44: "learned",
            45: "learned",
            46: "learned",
            47: "learned",
            48: "learned",
            49: "learned",
            50: "learned",
            51: "learned",
            52: "learned",
            53: "learned",
            54: "learned",
            55: "learning",
            56: "learned",
            57: "learning",
            58: "learned",
            59: "learned",
            j32: "learned",
            j53: "learned",
            j50: "learned",
            j10: "learned",
            j40: "learned",
            j13: "learned",
            j22: "learned",
            j56: "learned",
            j11: "learned",
            j4: "learning",
            j27: "learning",
            j23: "learned",
            j0: "learning",
            j8: "learned",
            j49: "learned",
            j36: "learned",
            j5: "learning",
            j35: "learned",
            j1: "learning",
            j3: "learning",
            j14: "learning",
            j18: "learned",
            j51: "learned",
            j34: "learned",
            j28: "learned",
            j44: "learned",
            j26: "learned",
            j33: "learned",
            j29: "learned",
            j21: "learned",
            j9: "learned",
            j47: "learned",
            j48: "learned",
            j12: "learned",
            j52: "learned",
            j38: "learned",
            j41: "learned",
            j24: "learned",
            j45: "learned",
            j55: "learned",
            j15: "learned",
            j7: "learning",
            j30: "learned",
            j59: "learned",
            j2: "learned",
            j6: "learned",
            j17: "learned",
            j42: "learned",
            j37: "learned",
            j58: "learned",
            j19: "learned",
            j20: "learning",
            j39: "learning",
            j46: "learned",
            j25: "learned",
            j43: "learned",
            j57: "learned",
            j54: "learned",
            j31: "learned",
            j16: "learning",
        },
        800: {
            0: "learned",
            1: "learning",
            2: "learned",
            3: "learned",
            4: "learned",
            j0: "learned",
        },
        stickers: { 702: true, 704: true, 708: true },
    },
];
